# Generated by Django 4.1.1 on 2022-09-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='observaoces',
            new_name='observacoes',
        ),
    ]
