# Generated by Django 4.1.1 on 2022-09-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_observaoces_transacao_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='valor',
            new_name='valorUnitario',
        ),
    ]
