# Generated by Django 4.1.1 on 2022-09-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_rename_valor_transacao_valorunitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='localCompra',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
